### ISSUE TITLE
The Configure.ac file does not find my apr and apr-util

### ISSUE THREAD

**Issue by DinoChiesa** [apigee/apib#11]
Disclaimer: I don't know autoconf

 but it seems to me the Configure.ac file assumes the apr is in /usr/include/apr-1 and the apr-util likewise.  Is this a standard location? 

I retrieved and built apr and apr-util for MACOSX but did not install them there. Instead they were  in /usr/local/apr/include/apr-1 and  /usr/local/apr-util/include/apr-1 . I couldn't figure out how to tell configure these locations .   So this is possibly a doc update, and possibly a change to configure.ac. 

I was able to get the build to succeed only by manually modifying the Makefile, to insert the -I/usr/local/apr/include/apr-1  etc.

**Comment by danfe** [comment]
Same problem affects FreeBSD.  No need to pollute global `CFLAGS`; just pass `APR_LOC="<whatever>/include/apr-1"` via environment when running `./configure` script.

**Comment by danfe** [comment]
I guess this issue is not longer relevant as recent versions of apib no longer use Apache Portable Runtime or GNU configure.
