### ISSUE TITLE
New switch to specify ciphersuite

### ISSUE THREAD

**Issue by JohnLHartman** [apigee/apib#14]
I have been using apib to test the performance of an embedded web server.

This is a small device, so the overhead of some ciphers can be significant.  I added an option to apib to specify the suite or suites to be offered to the server, using the OpenSSL names:
`./apib -C AES128-SHA:ECDHE-RSA-AES256-SHA384 https://10.28.22.4/index.html`

Diff attached
[apib.txt](https://github.com/apigee/apib/files/1250179/apib.txt)

With this option, apib has been of great help in testing and tweaking our device.   Thanks!

**Comment by gbrail** [comment]
Thanks for the patch -- I made one change, so that apib exits if the option is incorrect, but otherwise it looks good. Thanks!
