### ISSUE TITLE
FreeBSD support (for gathering CPU and memory statistics)

### ISSUE THREAD

**Issue by danfe** [apigee/apib#15]
Hi, thanks for the nice tool!  While porting it to FreeBSD, I've discovered that it lacks CPU and memory statistics collection code for this OS and [patched](https://svnweb.freebsd.org/ports/head/benchmarks/apib/files/patch-src_apib__cpu.c) it.  If you like the patch, it would be nice to see it included upstream, i.e., pushed to master. :-)

P.S.  Speaking of versions: existing `APIB_1_0` release tag is very old.  Perhaps it is time for the new version?  (Given that not too many changes had occurred during the time frame, it could probably be tagged as `1.1` or `v1.1`.)

**Comment by gbrail** [comment]
Thanks! I'm merging this patch manually and just making the build work on
the Mac again... I'll update the tag shortly!

**Comment by gbrail** [comment]
I updated the code in master and ensured that it builds (at least for me) on OS X and Linux.

I don't have a FreeBSD host -- can you test there! Then we can tag and update and stuff.

**Comment by danfe** [comment]
Seems to build and work fine under FreeBSD now, no patches needed.  Thanks!
