### ISSUE TITLE
"-nan" in json output

### ISSUE THREAD

**Issue by XanderStrike** [apigee/apib#18]
When compiled from master, I receive the following:

```
pivotal@astandke-scaling:~/apib$ ./apib -S -d 5 -N nantest https://astandke.com
nantest,25.799,38.5591,1,5.000,129,129,0,2,36.238,164.864,36.500,36.650,47.397,163.614,15.811-nan,-nan,-nan,4.18,0.00,0.00,0.01,0.56
```
(scroll to the right, note the `-nan`s)

I checked out an arbitrarily old commit (2a603ea4460ba96fce608edf3a14af0a95707d8b) and saw the output I expect:

```
pivotal@astandke-scaling:~/apib$ ./apib -S -d 5 -N nantest https://astandke.com
nantest,25.599,38.929,1,1,5.000,128,128,0,2,36.185,180.611,36.622,36.844,56.925,164.646,16.998,0,0,0,4,0,0,0.01,0.56
```

The version in homebrew seems to be correct though, so it's just something since then.

**Comment by gbrail** [comment]
When CPU counting wasn't available (and it often isn't) I fixed it to return 0.

https://github.com/apigee/apib/pull/20
