### ISSUE TITLE
columns don't match header output

### ISSUE THREAD

**Issue by smw1218** [apigee/apib#19]
I build from current master HEAD and I'm getting:
```
Name,Throughput,Avg. Latency,Threads,Connections,Duration,Completed,Successful,Errors,Sockets,Min. latency,Max. latency,50%% Latency,90%% Latency,98%% Latency,99%% Latency,Latency Std Dev,Avg Client CPU,Avg Server CPU,Avg Server 2 CPU,Client Mem Usage,Server Mem,Server 2 Mem,Avg. Send Bandwidth,Avg. Recv. Bandwidth
test,71.991,13.6991,1,1.000,72,72,0,73,11.751,52.649,13.035,14.236,19.313,52.649,4.791-nan,-nan,-nan,4.89,0.00,0.00,0.66,0.11
```

There are two missing fields in the output. Obviously a missing comma before the first -nan accounts for one. It appears based on reasonable numbers is that Duration is missing.

Also, the -nan is likely expected as I'm running this from a Docker container.

**Comment by gbrail** [comment]
I made some big changes a few weeks ago and I'm glad that you're using the
product as I clearly missed some test cases. These should be easy to fix
though, so let me take a look!

**Comment by gbrail** [comment]
Looks like we were missing one. Can you take a look? I'd like to see if we can get Homebrew to pick up this new version too:

https://github.com/apigee/apib/pull/20

**Comment by smw1218** [comment]
Looks good now. Thanks for the quick turnaround!
